
-- users
CREATE TABLE `articles` (
  `id`        INTEGER        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `title`     VARCHAR(1000)   NOT NULL,
  `body`      VARCHAR(1000)   NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
